dist: trusty
sudo: required

matrix:
  include:
  - os: osx
    osx_image: xcode6.4
    language: generic
    env:
    - TRAVIS_PYTHON_VERSION="2.7.12"
    - TURBODBC_TEST_CONFIGURATION_FILES="query_fixtures_postgresql.json"
    - ODBC_DIR=odbc_osx
#  Disable for now until a workaround for the detection of pyenv versions by pybind11
#  is found
#  - os: osx
#    language: generic
#    env:
#    - TRAVIS_PYTHON_VERSION="3.6.0"
#    - TURBODBC_TEST_CONFIGURATION_FILES="query_fixtures_postgresql.json"
#    - ODBC_DIR=odbc_osx
  - os: linux
    language: python
    python: "2.7"
    env:
    - TURBODBC_TEST_CONFIGURATION_FILES="query_fixtures_postgresql.json,query_fixtures_mysql.json"
    - ODBC_DIR=odbc
  - os: linux
    language: python
    python: "3.4"
    env:
    - TURBODBC_TEST_CONFIGURATION_FILES="query_fixtures_postgresql.json,query_fixtures_mysql.json"
    - ODBC_DIR=odbc
  - os: linux
    language: python
    python: "3.5"
    env:
    - TURBODBC_TEST_CONFIGURATION_FILES="query_fixtures_postgresql.json,query_fixtures_mysql.json"
    - ODBC_DIR=odbc
  - os: linux
    language: python
    python: "3.6"
    env:
    - TURBODBC_TEST_CONFIGURATION_FILES="query_fixtures_postgresql.json,query_fixtures_mysql.json"
    - ODBC_DIR=odbc


services:
  - mysql
  - postgresql

addons:
  apt:
    packages:
      - unixodbc
      - unixodbc-dev
      - libboost-date-time-dev
      - libboost-system-dev
      - libmyodbc
      - odbc-postgresql=1:09.02.0100-2ubuntu1

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew outdated pyenv || brew upgrade pyenv
    brew install unixodbc
    brew install pyenv-virtualenv
    brew install psqlodbc
    eval "$(pyenv init -)"
    pyenv install ${TRAVIS_PYTHON_VERSION}
    pyenv virtualenv ${TRAVIS_PYTHON_VERSION} turbodbc
    pyenv activate turbodbc
    python --version
    pip install pytest mock

    echo "Setting up preinstalled PostgreSQL database"
    rm -rf /usr/local/var/postgres
    initdb /usr/local/var/postgres
    pg_ctl -D /usr/local/var/postgres -w start
    createuser -s postgres
    psql -U postgres -c 'CREATE DATABASE test_db;'
    psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'password';"
  fi

install:
  - pip install numpy==1.8.0 six twine

before_script: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    $TRAVIS_BUILD_DIR/travis/setup_test_dbs.sh
  fi

script:
  - export ODBCSYSINI=${PWD}/travis/${ODBC_DIR}
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=./dist -DPYBIND11_PYTHON_VERSION=${TRAVIS_PYTHON_VERSION} ..
  - make -j4
  - ctest --verbose
  - make install
  - cd dist
  - python setup.py sdist
  - cd dist
  - pip install *.tar.gz
  - cd ..
  - rm -rf dist


deploy:
  skip_cleanup: true
  provider: pypi
  user: MathMagic
  password:
    secure: "A0Xv0/7EXcDUzevO3lLVr6OUg1wy1NrFKGwruHr0rUfdBBRmDHVm2njvuiRkPgMH0IiWw/HscxNvHYs1U1CpGsWLJ+/TLOc5UQEKl9kkopEAPrwgQeIg7jOiC6bUDgXbZ5iYU8PIl7ygpBNoGJ2sdIP4nwH1COtntSdVr3oy7VwcVge0QhvccYTt4b49YcaJ6rBMntBWo2UhFZ1PGGWrCbPJB+lhwOv1OkbIyV8jXQ3FrENJGIDQiVMoTdWdoYDPP05lFVrsADwD+TRxEdM7z+cIyFhTTUuabRbPDyRiUd69it2WfCRUb4r+fNeF1abh8GRkk5jE4RQWt/DJiZG/yqZU3SKvIf4/pxZywpmqIZr6CEAJ3iriHHN0Khv1fPnyJ6LJ+paOHcrkDKFTbOb32pOjOdDr9UVN5z7tHdN1MmrrMAbzaIcldLcHq69iocXfUWWR5H/CR43Tm422z0ILbMsdQ+z2epTG+l/qLs8ZxSjWeleMIff5n2x3k6U4QXcdwM8x8axYYgq9WoutI90/97zpvf0h8J8K5+Mr7ucNRLbsPU0OKMZknBOT0SRtJFxokDYZU0OCFLIukIlUYCRuh4es/9w30+kPExfhB5i7LKnpvILtPqIU6KDiUQe8mW1+GnnW/hk3WCdkLT6gwOBNBLVPoIJEuCcYjKdHksMrCnY="
  on:
    tags: true
    os: linux
    python: "2.7"
    branch: master
    repo: blue-yonder/turbodbc
