version: '{branch} - #{build}'

image: Visual Studio 2015

platform:
  - x64

environment:
  BOOST_ROOT: C:\Libraries\boost_1_63_0
  TURBODBC_TEST_CONFIGURATION_FILES: query_fixtures_postgresql.json,query_fixtures_mysql.json,query_fixtures_mssql.json
  MYSQL_PWD: Password12!
  PGUSER: postgres
  PGPASSWORD: Password12!

  matrix:
    # first group
    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6

    # second group
    - PYTHON: C:\Python35-x64
      PYTHON_VERSION: 3.5

    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7

services:
  - mysql
  - postgresql96
  - mssql2016

install:
- cmd: >-
    git submodule update --init --recursive

    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    pip install numpy pytest pytest-cov mock "pyarrow>=0.11,<0.12" pandas

    echo %PYTHON%

before_build:
#http://help.appveyor.com/discussions/problems/4569-the-target-_convertpdbfiles-listed-in-a-beforetargets-attribute-at-c-does-not-exist-in-the-project-and-will-be-ignored
- del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build_script:
- cmd: >-
    cd ..

    mkdir turbodbc_build

    cd turbodbc_build

    cmake ..\turbodbc -DPYBIND11_PYTHON_VERSION=%PYTHON_VERSION% -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=dist -A x64

    cmake --build . --config Release

test_script:
- cmd: >-
    reg import ..\turbodbc\appveyor\odbc-mysql.reg

    reg import ..\turbodbc\appveyor\odbc-postgresql.reg

    reg import ..\turbodbc\appveyor\odbc-mssql.reg

    reg import ..\turbodbc\appveyor\odbc-data-sources.reg

    SET PATH=C:\Program Files\PostgreSQL\9.6\bin;C:\Program Files\MySQL\MySQL Server 5.7\bin;%PATH%

    psql -c "CREATE DATABASE test_db;"

    mysql -u root -e "CREATE DATABASE test_db;"

    sqlcmd -S localhost\SQL2016 -U SA -P "Password12!" -Q "ALTER LOGIN SA WITH PASSWORD = 'StrongPassword1'"

    sqlcmd -S localhost\SQL2016 -U SA -P "StrongPassword1" -Q "CREATE DATABASE test_db"

    ctest --verbose -C Release

after_test:
  - cmake --build . --config Release --target install
  - pip install wheel pybind11==2.2.0
  - cd dist
  - python setup.py bdist_wheel
  - cd dist
  - cp turbodbc*.whl ..\..\..\turbodbc

artifacts:
- path: 'turbodbc*.whl'
  name: Binary wheel
